[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
RadialBasisFunctions = "79ee0514-adf7-4479-8807-6f72ea8967e8"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
